/**
 * This file was auto-generated by @openapi-qraft/cli.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/conversations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Conversations */
        get: operations["list_conversation_history_conversations_get"];
        put?: never;
        /** Create Conversation */
        post: operations["create_conversation_history_conversations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/conversations/{conversation_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Conversation */
        get: operations["get_conversation_history_conversations__conversation_id__get"];
        put?: never;
        post?: never;
        /** Delete Conversation */
        delete: operations["delete_conversation_history_conversations__conversation_id__delete"];
        options?: never;
        head?: never;
        /** Update Conversation */
        patch: operations["patch_conversation_history_conversations__conversation_id__patch"];
        trace?: never;
    };
    "/conversations/{conversation_id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Append Conversation Message */
        post: operations["append_message_to_conversation_conversations__conversation_id__messages_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Documents */
        get: operations["listDocuments"];
        put?: never;
        /** Upload Document */
        post: operations["uploadDocument"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search Documents */
        get: operations["searchDocuments"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents/{document_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Document */
        get: operations["getDocument"];
        put?: never;
        post?: never;
        /** Delete Document */
        delete: operations["deleteDocument"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents/{document_id}/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search Document */
        get: operations["searchDocument"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ingestion-jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Ingestion Job */
        get: operations["getIngestionJob"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/agents/chat-agent": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Langgraph Agent Endpoint */
        post: operations["langgraph_agent_endpoint_agents_chat_agent_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/agents/chat-agent/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Health check.
         */
        get: operations["health_agents_chat_agent_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ActivityMessage
         * @description An activity progress message emitted between chat messages.
         */
        ActivityMessage: {
            /** Id */
            id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            role: "activity";
            /** Activitytype */
            activityType: string;
            /** Content */
            content: {
                [key: string]: unknown;
            };
        } & {
            [key: string]: unknown;
        };
        /**
         * AssistantMessage
         * @description An assistant message.
         */
        AssistantMessage: {
            /** Id */
            id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            role: "assistant";
            /** Content */
            content?: string | null;
            /** Name */
            name?: string | null;
            /** Encryptedvalue */
            encryptedValue?: string | null;
            /** Toolcalls */
            toolCalls?: components["schemas"]["ToolCall"][] | null;
        } & {
            [key: string]: unknown;
        };
        /**
         * AudioInputContent
         * @description An audio input content fragment.
         */
        AudioInputContent: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "audio";
            /** Source */
            source: components["schemas"]["InputContentDataSource"] | components["schemas"]["InputContentUrlSource"];
            /** Metadata */
            metadata?: unknown | null;
        } & {
            [key: string]: unknown;
        };
        /**
         * BinaryInputContent
         * @description A deprecated binary payload reference in a multimodal user message.
         */
        BinaryInputContent: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "binary";
            /** Mimetype */
            mimeType: string;
            /** Id */
            id?: string | null;
            /** Url */
            url?: string | null;
            /** Data */
            data?: string | null;
            /** Filename */
            filename?: string | null;
        } & {
            [key: string]: unknown;
        };
        /** Body_uploadDocument */
        Body_uploadDocument: {
            /** File */
            file: string;
            /** Title */
            title: string;
            /** Metadata Json */
            metadata_json?: string | null;
        };
        /**
         * Context
         * @description Additional context for the agent.
         */
        Context: {
            /** Description */
            description: string;
            /** Value */
            value: string;
        } & {
            [key: string]: unknown;
        };
        /** ConversationCreate */
        ConversationCreate: {
            /** Title */
            title?: string | null;
            /** Active Document Ids */
            active_document_ids?: string[] | null;
        };
        /** ConversationListItem */
        ConversationListItem: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Title */
            title: string;
            status: components["schemas"]["ConversationStatus"];
            /** Active Document Ids */
            active_document_ids?: string[];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Archived At */
            archived_at?: string | null;
            /**
             * Message Count
             * @default 0
             */
            message_count: number;
        };
        /** ConversationListResponse */
        ConversationListResponse: {
            /** Items */
            items: components["schemas"]["ConversationListItem"][];
        };
        /** ConversationMessagePayload */
        ConversationMessagePayload: {
            /** Parent Id */
            parent_id?: string | null;
            /** Message */
            message: {
                [key: string]: unknown;
            };
            /** Run Config */
            run_config?: {
                [key: string]: unknown;
            } | null;
            /** State Snapshot */
            state_snapshot?: {
                [key: string]: unknown;
            } | null;
        };
        /** ConversationMessageRead */
        ConversationMessageRead: {
            /** Parent Id */
            parent_id?: string | null;
            /** Message */
            message: {
                [key: string]: unknown;
            };
            /** Run Config */
            run_config?: {
                [key: string]: unknown;
            } | null;
            /** State Snapshot */
            state_snapshot?: {
                [key: string]: unknown;
            } | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Message Id */
            message_id: string;
            /** Sort Index */
            sort_index: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ConversationRead */
        ConversationRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Title */
            title: string;
            status: components["schemas"]["ConversationStatus"];
            /** Active Document Ids */
            active_document_ids?: string[];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Archived At */
            archived_at?: string | null;
            /**
             * Message Count
             * @default 0
             */
            message_count: number;
            /** Messages */
            messages?: components["schemas"]["ConversationMessageRead"][];
        };
        /**
         * ConversationStatus
         * @enum {string}
         */
        ConversationStatus: "regular" | "archived" | "deleted";
        /** ConversationUpdate */
        ConversationUpdate: {
            /** Title */
            title?: string | null;
            status?: components["schemas"]["ConversationStatus"] | null;
            /** Active Document Ids */
            active_document_ids?: string[] | null;
        };
        /**
         * DeveloperMessage
         * @description A developer message.
         */
        DeveloperMessage: {
            /** Id */
            id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            role: "developer";
            /** Content */
            content: string;
            /** Name */
            name?: string | null;
            /** Encryptedvalue */
            encryptedValue?: string | null;
        } & {
            [key: string]: unknown;
        };
        /** DocumentCreateResponse */
        DocumentCreateResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Title */
            title: string;
            status: components["schemas"]["DocumentStatus"];
            /**
             * Uploaded At
             * Format: date-time
             */
            uploaded_at: string;
            /**
             * Ingestion Job Id
             * Format: uuid
             */
            ingestion_job_id: string;
        };
        /**
         * DocumentInputContent
         * @description A document input content fragment.
         */
        DocumentInputContent: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "document";
            /** Source */
            source: components["schemas"]["InputContentDataSource"] | components["schemas"]["InputContentUrlSource"];
            /** Metadata */
            metadata?: unknown | null;
        } & {
            [key: string]: unknown;
        };
        /** DocumentListItem */
        DocumentListItem: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Title */
            title: string;
            /** Original Filename */
            original_filename: string;
            /** Mime Type */
            mime_type: string;
            /** Size Bytes */
            size_bytes: number;
            status: components["schemas"]["DocumentStatus"];
            /**
             * Uploaded At
             * Format: date-time
             */
            uploaded_at: string;
            /** Indexed At */
            indexed_at?: string | null;
        };
        /** DocumentListResponse */
        DocumentListResponse: {
            /** Items */
            items: components["schemas"]["DocumentListItem"][];
        };
        /** DocumentRead */
        DocumentRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Title */
            title: string;
            /** Original Filename */
            original_filename: string;
            /** Mime Type */
            mime_type: string;
            /** Size Bytes */
            size_bytes: number;
            status: components["schemas"]["DocumentStatus"];
            /**
             * Uploaded At
             * Format: date-time
             */
            uploaded_at: string;
            /** Indexed At */
            indexed_at?: string | null;
            /** Storage Bucket */
            storage_bucket: string;
            /** Storage Object Key */
            storage_object_key: string;
            /** Sha256 */
            sha256: string;
            /** Metadata Json */
            metadata_json: {
                [key: string]: unknown;
            };
            /** Download Url */
            download_url?: string | null;
            /** Preview Url */
            preview_url?: string | null;
            /** Deleted At */
            deleted_at?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** DocumentSearchResponse */
        DocumentSearchResponse: {
            /** Query */
            query: string;
            /** Items */
            items: components["schemas"]["DocumentSearchResult"][];
        };
        /** DocumentSearchResult */
        DocumentSearchResult: {
            /**
             * Chunk Id
             * Format: uuid
             */
            chunk_id: string;
            /**
             * Document Id
             * Format: uuid
             */
            document_id: string;
            /** Document Title */
            document_title?: string | null;
            /** Document Original Filename */
            document_original_filename?: string | null;
            /** Page Number */
            page_number?: number | null;
            /** Snippet */
            snippet: string;
        };
        /**
         * DocumentStatus
         * @enum {string}
         */
        DocumentStatus: "uploaded" | "processing" | "ready" | "failed" | "deleted";
        /**
         * FunctionCall
         * @description Name and arguments of a function call.
         */
        FunctionCall: {
            /** Name */
            name: string;
            /** Arguments */
            arguments: string;
        } & {
            [key: string]: unknown;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * ImageInputContent
         * @description An image input content fragment.
         */
        ImageInputContent: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "image";
            /** Source */
            source: components["schemas"]["InputContentDataSource"] | components["schemas"]["InputContentUrlSource"];
            /** Metadata */
            metadata?: unknown | null;
        } & {
            [key: string]: unknown;
        };
        /** IngestionJobRead */
        IngestionJobRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Document Id
             * Format: uuid
             */
            document_id: string;
            /** Rq Job Id */
            rq_job_id?: string | null;
            status: components["schemas"]["IngestionJobStatus"];
            stage: components["schemas"]["IngestionJobStage"];
            /** Is Current */
            is_current: boolean;
            /** Attempt Count */
            attempt_count: number;
            /** Error Message */
            error_message?: string | null;
            /** Embedding Provider */
            embedding_provider: string;
            /** Embedding Model */
            embedding_model: string;
            /** Embedding Dimensions */
            embedding_dimensions: number;
            /** Embedding Task Type */
            embedding_task_type: string;
            /** Chunk Size */
            chunk_size: number;
            /** Chunk Overlap */
            chunk_overlap: number;
            /** Job Metadata Json */
            job_metadata_json: {
                [key: string]: unknown;
            };
            /** Started At */
            started_at?: string | null;
            /** Finished At */
            finished_at?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * IngestionJobStage
         * @enum {string}
         */
        IngestionJobStage: "queued" | "extracting" | "chunking" | "embedding" | "indexing" | "completed" | "failed";
        /**
         * IngestionJobStatus
         * @enum {string}
         */
        IngestionJobStatus: "queued" | "started" | "succeeded" | "failed";
        /**
         * InputContentDataSource
         * @description Inline base64-encoded source.
         */
        InputContentDataSource: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "data";
            /** Value */
            value: string;
            /** Mimetype */
            mimeType: string;
        } & {
            [key: string]: unknown;
        };
        /**
         * InputContentUrlSource
         * @description URL-referenced source.
         */
        InputContentUrlSource: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "url";
            /** Value */
            value: string;
            /** Mimetype */
            mimeType?: string | null;
        } & {
            [key: string]: unknown;
        };
        /**
         * ReasoningMessage
         * @description A reasoning message containing the agent's internal reasoning process.
         */
        ReasoningMessage: {
            /** Id */
            id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            role: "reasoning";
            /** Content */
            content: string;
            /** Encryptedvalue */
            encryptedValue?: string | null;
        } & {
            [key: string]: unknown;
        };
        /**
         * RunAgentInput
         * @description Input for running an agent.
         */
        RunAgentInput: {
            /** Threadid */
            threadId: string;
            /** Runid */
            runId: string;
            /** Parentrunid */
            parentRunId?: string | null;
            /** State */
            state: unknown;
            /** Messages */
            messages: (components["schemas"]["DeveloperMessage"] | components["schemas"]["SystemMessage"] | components["schemas"]["AssistantMessage"] | components["schemas"]["UserMessage"] | components["schemas"]["ToolMessage"] | components["schemas"]["ActivityMessage"] | components["schemas"]["ReasoningMessage"])[];
            /** Tools */
            tools: components["schemas"]["Tool"][];
            /** Context */
            context: components["schemas"]["Context"][];
            /** Forwardedprops */
            forwardedProps: unknown;
        } & {
            [key: string]: unknown;
        };
        /**
         * SystemMessage
         * @description A system message.
         */
        SystemMessage: {
            /** Id */
            id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            role: "system";
            /** Content */
            content: string;
            /** Name */
            name?: string | null;
            /** Encryptedvalue */
            encryptedValue?: string | null;
        } & {
            [key: string]: unknown;
        };
        /**
         * TextInputContent
         * @description A text fragment in a multimodal user message.
         */
        TextInputContent: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "text";
            /** Text */
            text: string;
        } & {
            [key: string]: unknown;
        };
        /**
         * Tool
         * @description A tool definition.
         */
        Tool: {
            /** Name */
            name: string;
            /** Description */
            description: string;
            /** Parameters */
            parameters?: unknown | null;
        } & {
            [key: string]: unknown;
        };
        /**
         * ToolCall
         * @description A tool call, modelled after OpenAI tool calls.
         */
        ToolCall: {
            /** Id */
            id: string;
            /**
             * Type
             * @default function
             * @constant
             */
            type: "function";
            function: components["schemas"]["FunctionCall"];
            /** Encryptedvalue */
            encryptedValue?: string | null;
        } & {
            [key: string]: unknown;
        };
        /**
         * ToolMessage
         * @description A tool result message.
         */
        ToolMessage: {
            /** Id */
            id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            role: "tool";
            /** Content */
            content: string;
            /** Toolcallid */
            toolCallId: string;
            /** Error */
            error?: string | null;
            /** Encryptedvalue */
            encryptedValue?: string | null;
        } & {
            [key: string]: unknown;
        };
        /**
         * UserMessage
         * @description A user message supporting text or multimodal content.
         */
        UserMessage: {
            /** Id */
            id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            role: "user";
            /** Content */
            content: string | (components["schemas"]["TextInputContent"] | components["schemas"]["ImageInputContent"] | components["schemas"]["AudioInputContent"] | components["schemas"]["VideoInputContent"] | components["schemas"]["DocumentInputContent"] | components["schemas"]["BinaryInputContent"])[];
            /** Name */
            name?: string | null;
            /** Encryptedvalue */
            encryptedValue?: string | null;
        } & {
            [key: string]: unknown;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * VideoInputContent
         * @description A video input content fragment.
         */
        VideoInputContent: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "video";
            /** Source */
            source: components["schemas"]["InputContentDataSource"] | components["schemas"]["InputContentUrlSource"];
            /** Metadata */
            metadata?: unknown | null;
        } & {
            [key: string]: unknown;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_conversation_history_conversations_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationListResponse"];
                };
            };
        };
    };
    create_conversation_history_conversations_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConversationCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_conversation_history_conversations__conversation_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_conversation_history_conversations__conversation_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_conversation_history_conversations__conversation_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConversationUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    append_message_to_conversation_conversations__conversation_id__messages_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConversationMessagePayload"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listDocuments: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentListResponse"];
                };
            };
        };
    };
    uploadDocument: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_uploadDocument"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentCreateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    searchDocuments: {
        parameters: {
            query: {
                q: string;
                document_ids?: string[] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentSearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getDocument: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    deleteDocument: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    searchDocument: {
        parameters: {
            query: {
                q: string;
            };
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentSearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getIngestionJob: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestionJobRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    langgraph_agent_endpoint_agents_chat_agent_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunAgentInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_agents_chat_agent_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
