from app.services.ingestion.constants import (
    DEFAULT_EMBEDDING_BATCH_SIZE,
    DEFAULT_EMBEDDING_DIMENSIONS,
    DEFAULT_EMBEDDING_MODEL,
    DEFAULT_EMBEDDING_PROVIDER,
    DEFAULT_EMBEDDING_TASK_TYPE,
    DEFAULT_INGESTION_CHUNK_OVERLAP,
    DEFAULT_INGESTION_CHUNK_SIZE,
    INGESTION_QUEUE_NAME,
    SUPPORTED_INGESTION_FILE_EXTENSION,
    SUPPORTED_INGESTION_MIME_TYPE,
)

__all__ = [
    "DEFAULT_EMBEDDING_BATCH_SIZE",
    "DEFAULT_EMBEDDING_DIMENSIONS",
    "DEFAULT_EMBEDDING_MODEL",
    "DEFAULT_EMBEDDING_PROVIDER",
    "DEFAULT_EMBEDDING_TASK_TYPE",
    "DEFAULT_INGESTION_CHUNK_OVERLAP",
    "DEFAULT_INGESTION_CHUNK_SIZE",
    "INGESTION_QUEUE_NAME",
    "SUPPORTED_INGESTION_FILE_EXTENSION",
    "SUPPORTED_INGESTION_MIME_TYPE",
]
