"""create initial document library schema

Revision ID: 4097d288a0f6
Revises: 
Create Date: 2026-04-02 18:15:13.782069

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4097d288a0f6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS pgcrypto")
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.create_table('documents',
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('original_filename', sa.Text(), nullable=False),
    sa.Column('storage_bucket', sa.String(), nullable=False),
    sa.Column('storage_object_key', sa.Text(), nullable=False),
    sa.Column('mime_type', sa.String(), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('sha256', sa.String(), nullable=False),
    sa.Column('status', sa.String(), server_default=sa.text("'uploaded'"), nullable=False),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('indexed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('uploaded', 'processing', 'ready', 'failed', 'deleted')", name='ck_documents_status_valid'),
    sa.CheckConstraint('size_bytes >= 0', name='ck_documents_size_bytes_non_negative'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_documents_sha256', 'documents', ['sha256'], unique=False)
    op.create_index('ix_documents_status', 'documents', ['status'], unique=False)
    op.create_index('ix_documents_uploaded_at', 'documents', ['uploaded_at'], unique=False)
    op.create_index('uq_documents_storage_location', 'documents', ['storage_bucket', 'storage_object_key'], unique=True)
    op.create_table('ingestion_jobs',
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('rq_job_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), server_default=sa.text("'queued'"), nullable=False),
    sa.Column('stage', sa.String(), server_default=sa.text("'queued'"), nullable=False),
    sa.Column('is_current', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('attempt_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('embedding_provider', sa.String(), nullable=False),
    sa.Column('embedding_model', sa.String(), nullable=False),
    sa.Column('embedding_dimensions', sa.Integer(), nullable=False),
    sa.Column('embedding_task_type', sa.String(), nullable=False),
    sa.Column('chunk_size', sa.Integer(), nullable=False),
    sa.Column('chunk_overlap', sa.Integer(), nullable=False),
    sa.Column('job_metadata_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("stage IN ('queued', 'extracting', 'chunking', 'embedding', 'indexing', 'completed', 'failed')", name='ck_ingestion_jobs_stage_valid'),
    sa.CheckConstraint("status IN ('queued', 'started', 'succeeded', 'failed')", name='ck_ingestion_jobs_status_valid'),
    sa.CheckConstraint('attempt_count >= 0', name='ck_ingestion_jobs_attempt_count_non_negative'),
    sa.CheckConstraint('chunk_overlap >= 0', name='ck_ingestion_jobs_chunk_overlap_non_negative'),
    sa.CheckConstraint('chunk_size > 0', name='ck_ingestion_jobs_chunk_size_positive'),
    sa.CheckConstraint('embedding_dimensions = 1536', name='ck_ingestion_jobs_embedding_dimensions'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rq_job_id')
    )
    op.create_index('ix_ingestion_jobs_document_id_created_at', 'ingestion_jobs', ['document_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index('uq_ingestion_jobs_current_per_document', 'ingestion_jobs', ['document_id'], unique=True, postgresql_where=sa.text('is_current'))
    op.create_table('document_chunks',
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('ingestion_job_id', sa.UUID(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('section_title', sa.Text(), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('embedding', Vector(dim=1536), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('chunk_index >= 0', name='ck_document_chunks_chunk_index_non_negative'),
    sa.CheckConstraint('page_number IS NULL OR page_number > 0', name='ck_document_chunks_page_number_positive'),
    sa.CheckConstraint('token_count IS NULL OR token_count >= 0', name='ck_document_chunks_token_count_non_negative'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ingestion_job_id'], ['ingestion_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_document_chunks_document_id', 'document_chunks', ['document_id'], unique=False)
    op.create_index('ix_document_chunks_embedding_hnsw', 'document_chunks', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_index('ix_document_chunks_ingestion_job_id', 'document_chunks', ['ingestion_job_id'], unique=False)
    op.create_index('uq_document_chunks_ingestion_job_chunk_index', 'document_chunks', ['ingestion_job_id', 'chunk_index'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_document_chunks_ingestion_job_chunk_index', table_name='document_chunks')
    op.drop_index('ix_document_chunks_ingestion_job_id', table_name='document_chunks')
    op.drop_index('ix_document_chunks_embedding_hnsw', table_name='document_chunks', postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_index('ix_document_chunks_document_id', table_name='document_chunks')
    op.drop_table('document_chunks')
    op.drop_index('uq_ingestion_jobs_current_per_document', table_name='ingestion_jobs', postgresql_where=sa.text('is_current'))
    op.drop_index('ix_ingestion_jobs_document_id_created_at', table_name='ingestion_jobs')
    op.drop_table('ingestion_jobs')
    op.drop_index('uq_documents_storage_location', table_name='documents')
    op.drop_index('ix_documents_uploaded_at', table_name='documents')
    op.drop_index('ix_documents_status', table_name='documents')
    op.drop_index('ix_documents_sha256', table_name='documents')
    op.drop_table('documents')
    # ### end Alembic commands ###
