"""remove unused document chunk fields

Revision ID: 7effd58d4c06
Revises: a683ef62be1b
Create Date: 2026-04-02 20:25:17.737442

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7effd58d4c06'
down_revision: Union[str, Sequence[str], None] = 'a683ef62be1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("document_chunks", "section_title")
    op.drop_column("document_chunks", "token_count")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "document_chunks",
        sa.Column("token_count", sa.Integer(), nullable=True),
    )
    op.create_check_constraint(
        "ck_document_chunks_token_count_non_negative",
        "document_chunks",
        "token_count IS NULL OR token_count >= 0",
    )
    op.add_column(
        "document_chunks",
        sa.Column("section_title", sa.Text(), nullable=True),
    )
    # ### end Alembic commands ###
