/**
 * This file was auto-generated by @openapi-qraft/cli.
 * Do not make direct changes to the file.
 */

import type { paths } from "../schema";
import type { DeepReadonly, InvalidateQueryFilters, MutationFiltersByMutationKey, MutationFiltersByParameters, MutationVariables, OperationError, OperationInfiniteData, PartialParameters, QueryFiltersByParameters, QueryFiltersByQueryKey, QueryFnOptionsByParameters, QueryFnOptionsByQueryKey, RequestFnResponse, ServiceOperationEnsureInfiniteQueryDataOptions, ServiceOperationEnsureQueryDataOptions, ServiceOperationFetchInfiniteQueryOptions, ServiceOperationFetchQueryOptions, ServiceOperationInfiniteQueryKey, ServiceOperationMutationFnOptions, ServiceOperationMutationKey, ServiceOperationQueryKey, ServiceOperationUseMutationOptions, UseQueryOptionsForUseQueries, UseQueryOptionsForUseSuspenseQuery, WithOptional, QraftServiceOperationsToken } from "@openapi-qraft/tanstack-query-react-types";
import type { CancelOptions, DefinedInitialDataInfiniteOptions, DefinedInitialDataOptions, DefinedUseInfiniteQueryResult, DefinedUseQueryResult, InfiniteQueryPageParamsOptions, InvalidateOptions, Mutation, MutationCache, MutationState, NoInfer, QueryState, RefetchOptions, ResetOptions, SetDataOptions, UndefinedInitialDataInfiniteOptions, UndefinedInitialDataOptions, Updater, UseInfiniteQueryResult, UseMutationResult, UseQueryResult, UseSuspenseInfiniteQueryOptions, UseSuspenseInfiniteQueryResult, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
export interface AgentsService {
    /** @summary Langgraph Agent Endpoint */
    langgraphAgentEndpointAgentsChatAgentPost: {
        /** @summary Langgraph Agent Endpoint */
        <TMeta extends Record<string, any>, TSignal extends AbortSignal = AbortSignal>(options: ServiceOperationMutationFnOptions<LanggraphAgentEndpointAgentsChatAgentPostBody, LanggraphAgentEndpointAgentsChatAgentPostParameters, TMeta, TSignal>, client?: (schema: LanggraphAgentEndpointAgentsChatAgentPostSchema, options: ServiceOperationMutationFnOptions<LanggraphAgentEndpointAgentsChatAgentPostBody, LanggraphAgentEndpointAgentsChatAgentPostParameters, TMeta, TSignal>) => Promise<RequestFnResponse<LanggraphAgentEndpointAgentsChatAgentPostData, LanggraphAgentEndpointAgentsChatAgentPostError>>): Promise<RequestFnResponse<LanggraphAgentEndpointAgentsChatAgentPostData, LanggraphAgentEndpointAgentsChatAgentPostError>>;
        /** @summary Langgraph Agent Endpoint */
        getMutationKey(parameters: DeepReadonly<LanggraphAgentEndpointAgentsChatAgentPostParameters> | void): ServiceOperationMutationKey<LanggraphAgentEndpointAgentsChatAgentPostSchema, LanggraphAgentEndpointAgentsChatAgentPostParameters>;
        /**
         * Enables performing asynchronous data mutation operations such as POST, PUT, PATCH, or DELETE requests.
         * Handles loading state, optimistic updates, and error handling.
         *
         * @summary Langgraph Agent Endpoint
         * @see {@link https://openapi-qraft.github.io/openapi-qraft/docs/hooks/useMutation|`useMutation(...)` documentation}
         * @example Mutation with predefined parameters, e.g., for updating
         * ```ts
         * const { mutate, isPending } = qraft.agents.langgraphAgentEndpointAgentsChatAgentPost.useMutation({})
         * mutate(body);
         * ```
         * @example Mutation without predefined parameters, e.g., for creating
         * ```ts
         * const { mutate, isPending } = qraft.agents.langgraphAgentEndpointAgentsChatAgentPost.useMutation()
         * mutate({
         *     body: bodyPayload
         * });
         * ```
         */
        useMutation<TVariables extends LanggraphAgentEndpointAgentsChatAgentPostBody, TContext = unknown>(parameters: DeepReadonly<LanggraphAgentEndpointAgentsChatAgentPostParameters>, options?: ServiceOperationUseMutationOptions<LanggraphAgentEndpointAgentsChatAgentPostSchema, LanggraphAgentEndpointAgentsChatAgentPostData, LanggraphAgentEndpointAgentsChatAgentPostParameters, TVariables, OperationError<LanggraphAgentEndpointAgentsChatAgentPostError>, TContext>): UseMutationResult<LanggraphAgentEndpointAgentsChatAgentPostData, OperationError<LanggraphAgentEndpointAgentsChatAgentPostError>, TVariables, TContext>;
        /**
         * Enables performing asynchronous data mutation operations such as POST, PUT, PATCH, or DELETE requests.
         * Handles loading state, optimistic updates, and error handling.
         *
         * @summary Langgraph Agent Endpoint
         * @see {@link https://openapi-qraft.github.io/openapi-qraft/docs/hooks/useMutation|`useMutation(...)` documentation}
         * @example Mutation with predefined parameters, e.g., for updating
         * ```ts
         * const { mutate, isPending } = qraft.agents.langgraphAgentEndpointAgentsChatAgentPost.useMutation({})
         * mutate(body);
         * ```
         * @example Mutation without predefined parameters, e.g., for creating
         * ```ts
         * const { mutate, isPending } = qraft.agents.langgraphAgentEndpointAgentsChatAgentPost.useMutation()
         * mutate({
         *     body: bodyPayload
         * });
         * ```
         */
        useMutation<TVariables extends MutationVariables<LanggraphAgentEndpointAgentsChatAgentPostBody, LanggraphAgentEndpointAgentsChatAgentPostParameters>, TContext = unknown>(parameters: void, options?: ServiceOperationUseMutationOptions<LanggraphAgentEndpointAgentsChatAgentPostSchema, LanggraphAgentEndpointAgentsChatAgentPostData, LanggraphAgentEndpointAgentsChatAgentPostParameters, TVariables, OperationError<LanggraphAgentEndpointAgentsChatAgentPostError>, TContext>): UseMutationResult<LanggraphAgentEndpointAgentsChatAgentPostData, OperationError<LanggraphAgentEndpointAgentsChatAgentPostError>, TVariables, TContext>;
        /**
         * Returns the count of currently in-progress mutations.
         *
         * @summary Langgraph Agent Endpoint
         * @see {@link https://openapi-qraft.github.io/openapi-qraft/docs/hooks/useIsMutating|`useIsMutating(...)` documentation}
         * @example Check how many mutations are currently in progress for the specified service method.
         * ```ts
         * const langgraphAgentEndpointAgentsChatAgentPostTotal = qraft.agents.langgraphAgentEndpointAgentsChatAgentPost.useIsMutating()
         * ```
         * @example Check how many mutations are currently in progress with the specified parameters.
         * ```ts
         * const langgraphAgentEndpointAgentsChatAgentPostTotal = qraft.agents.langgraphAgentEndpointAgentsChatAgentPost.useIsMutating({
         *     parameters: {}
         * })
         * ```
         */
        useIsMutating<TContext = unknown>(filters?: MutationFiltersByParameters<LanggraphAgentEndpointAgentsChatAgentPostBody, LanggraphAgentEndpointAgentsChatAgentPostData, LanggraphAgentEndpointAgentsChatAgentPostParameters, OperationError<LanggraphAgentEndpointAgentsChatAgentPostError>, TContext> | MutationFiltersByMutationKey<LanggraphAgentEndpointAgentsChatAgentPostSchema, LanggraphAgentEndpointAgentsChatAgentPostBody, LanggraphAgentEndpointAgentsChatAgentPostData, LanggraphAgentEndpointAgentsChatAgentPostParameters, OperationError<LanggraphAgentEndpointAgentsChatAgentPostError>, TContext>): number;
        /**
         * Provides access to the current state of a mutation, including its status, any resulting data, and associated errors.
         *
         * @summary Langgraph Agent Endpoint
         * @see {@link https://openapi-qraft.github.io/openapi-qraft/docs/hooks/useMutationState|`useMutationState(...)` documentation}
         * @example Get all variables of all running mutations.
         * ```ts
         * const langgraphAgentEndpointAgentsChatAgentPostPendingMutationVariables = qraft.agents.langgraphAgentEndpointAgentsChatAgentPost.useMutationState({
         *     filters: {
         *         status: "pending"
         *     },
         *     select: mutation => mutation.state.variables
         * })
         * ```
         * @example Get all data for specific mutations via the `parameters`.
         * ```ts
         * const langgraphAgentEndpointAgentsChatAgentPostMutationData = qraft.agents.langgraphAgentEndpointAgentsChatAgentPost.useMutationState({
         *     filters: {
         *         parameters: {}
         *     },
         *     select: mutation => mutation.state.data
         * })
         * ```
         */
        useMutationState<TContext = unknown, TResult = MutationState<LanggraphAgentEndpointAgentsChatAgentPostData, OperationError<LanggraphAgentEndpointAgentsChatAgentPostError>, MutationVariables<LanggraphAgentEndpointAgentsChatAgentPostBody, LanggraphAgentEndpointAgentsChatAgentPostParameters>, TContext>>(options?: {
            filters?: MutationFiltersByParameters<LanggraphAgentEndpointAgentsChatAgentPostBody, LanggraphAgentEndpointAgentsChatAgentPostData, LanggraphAgentEndpointAgentsChatAgentPostParameters, OperationError<LanggraphAgentEndpointAgentsChatAgentPostError>, TContext> | MutationFiltersByMutationKey<LanggraphAgentEndpointAgentsChatAgentPostSchema, LanggraphAgentEndpointAgentsChatAgentPostBody, LanggraphAgentEndpointAgentsChatAgentPostData, LanggraphAgentEndpointAgentsChatAgentPostParameters, OperationError<LanggraphAgentEndpointAgentsChatAgentPostError>, TContext>;
            select?: (mutation: Mutation<LanggraphAgentEndpointAgentsChatAgentPostData, OperationError<LanggraphAgentEndpointAgentsChatAgentPostError>, MutationVariables<LanggraphAgentEndpointAgentsChatAgentPostBody, LanggraphAgentEndpointAgentsChatAgentPostParameters>, TContext>) => TResult;
        }): Array<TResult>;
        /** @summary Langgraph Agent Endpoint */
        isMutating<TContext>(filters?: MutationFiltersByParameters<LanggraphAgentEndpointAgentsChatAgentPostBody, LanggraphAgentEndpointAgentsChatAgentPostData, LanggraphAgentEndpointAgentsChatAgentPostParameters, OperationError<LanggraphAgentEndpointAgentsChatAgentPostError>, TContext> | MutationFiltersByMutationKey<LanggraphAgentEndpointAgentsChatAgentPostSchema, LanggraphAgentEndpointAgentsChatAgentPostBody, LanggraphAgentEndpointAgentsChatAgentPostData, LanggraphAgentEndpointAgentsChatAgentPostParameters, OperationError<LanggraphAgentEndpointAgentsChatAgentPostError>, TContext>): number;
        /**
         * Returns a `MutationCache` object that provides access to mutation cache operations
         * for the specific endpoint.
         *
         * @summary Langgraph Agent Endpoint
         * @see {@link https://openapi-qraft.github.io/openapi-qraft/docs/query-client/getMutationCache|`getMutationCache(...)` documentation}
         *
         * @example Find a mutation with specific parameters
         * ```ts
         * const mutationCache = qraft.agents.langgraphAgentEndpointAgentsChatAgentPost.getMutationCache();
         * const mutation = mutationCache.find({
         *     parameters: {}
         * });
         * ```
         *
         * @example Find all mutations for the endpoint
         * ```ts
         * const mutationCache = qraft.agents.langgraphAgentEndpointAgentsChatAgentPost.getMutationCache();
         * const mutations = mutationCache.findAll();
         * ```
         */
        getMutationCache(): Omit<MutationCache, "find" | "findAll"> & {
            find<TContext = unknown>(filters: MutationFiltersByParameters<LanggraphAgentEndpointAgentsChatAgentPostBody, LanggraphAgentEndpointAgentsChatAgentPostData, LanggraphAgentEndpointAgentsChatAgentPostParameters, OperationError<LanggraphAgentEndpointAgentsChatAgentPostError>, TContext> | MutationFiltersByMutationKey<LanggraphAgentEndpointAgentsChatAgentPostSchema, LanggraphAgentEndpointAgentsChatAgentPostBody, LanggraphAgentEndpointAgentsChatAgentPostData, LanggraphAgentEndpointAgentsChatAgentPostParameters, OperationError<LanggraphAgentEndpointAgentsChatAgentPostError>, TContext>): Mutation<LanggraphAgentEndpointAgentsChatAgentPostData, LanggraphAgentEndpointAgentsChatAgentPostError, MutationVariables<LanggraphAgentEndpointAgentsChatAgentPostBody, LanggraphAgentEndpointAgentsChatAgentPostParameters>, TContext> | undefined;
            findAll<TContext = unknown>(filters?: MutationFiltersByParameters<LanggraphAgentEndpointAgentsChatAgentPostBody, LanggraphAgentEndpointAgentsChatAgentPostData, LanggraphAgentEndpointAgentsChatAgentPostParameters, OperationError<LanggraphAgentEndpointAgentsChatAgentPostError>, TContext> | MutationFiltersByMutationKey<LanggraphAgentEndpointAgentsChatAgentPostSchema, LanggraphAgentEndpointAgentsChatAgentPostBody, LanggraphAgentEndpointAgentsChatAgentPostData, LanggraphAgentEndpointAgentsChatAgentPostParameters, OperationError<LanggraphAgentEndpointAgentsChatAgentPostError>, TContext>): Array<Mutation<LanggraphAgentEndpointAgentsChatAgentPostData, LanggraphAgentEndpointAgentsChatAgentPostError, MutationVariables<LanggraphAgentEndpointAgentsChatAgentPostBody, LanggraphAgentEndpointAgentsChatAgentPostParameters>, TContext>>;
        };
        schema: LanggraphAgentEndpointAgentsChatAgentPostSchema;
        types: {
            parameters: LanggraphAgentEndpointAgentsChatAgentPostParameters;
            data: LanggraphAgentEndpointAgentsChatAgentPostData;
            error: LanggraphAgentEndpointAgentsChatAgentPostError;
            body: LanggraphAgentEndpointAgentsChatAgentPostBody;
        };
    };
    /**
     * @summary Health
     * @description Health check.
     */
    healthAgentsChatAgentHealthGet: {
        /**
         * @summary Health
         * @description Health check.
         */
        <TMeta extends Record<string, any>, TSignal extends AbortSignal = AbortSignal>(options: QueryFnOptionsByQueryKey<HealthAgentsChatAgentHealthGetSchema, HealthAgentsChatAgentHealthGetParameters, TMeta, TSignal> | (QueryFnOptionsByParameters<HealthAgentsChatAgentHealthGetParameters, TMeta, TSignal> | void), client?: (schema: HealthAgentsChatAgentHealthGetSchema, options: {
            parameters: HealthAgentsChatAgentHealthGetParameters;
            signal?: TSignal;
            meta?: TMeta;
        }) => Promise<RequestFnResponse<HealthAgentsChatAgentHealthGetData, HealthAgentsChatAgentHealthGetError>>): Promise<RequestFnResponse<HealthAgentsChatAgentHealthGetData, HealthAgentsChatAgentHealthGetError>>;
        /**
         * @summary Health
         * @description Health check.
         */
        getQueryKey(parameters: DeepReadonly<HealthAgentsChatAgentHealthGetParameters> | void): ServiceOperationQueryKey<HealthAgentsChatAgentHealthGetSchema, HealthAgentsChatAgentHealthGetParameters>;
        /**
         * Performs asynchronous data fetching, manages loading states and error handling.
         *
         * @summary Health
         * @description Health check.
         * @see {@link https://openapi-qraft.github.io/openapi-qraft/docs/hooks/useQuery|`useQuery(...)` documentation}
         * @example Query without parameters
         * ```ts
         * const { data, isLoading } = qraft.agents.healthAgentsChatAgentHealthGet.useQuery()
         * ```
         */
        useQuery<TData = HealthAgentsChatAgentHealthGetData>(parameters: ServiceOperationQueryKey<HealthAgentsChatAgentHealthGetSchema, HealthAgentsChatAgentHealthGetParameters> | (DeepReadonly<HealthAgentsChatAgentHealthGetParameters> | void), options?: Omit<UndefinedInitialDataOptions<HealthAgentsChatAgentHealthGetData, HealthAgentsChatAgentHealthGetError, TData, ServiceOperationQueryKey<HealthAgentsChatAgentHealthGetSchema, HealthAgentsChatAgentHealthGetParameters>>, "queryKey">): UseQueryResult<TData, OperationError<HealthAgentsChatAgentHealthGetError>>;
        /**
         * Performs asynchronous data fetching, manages loading states and error handling.
         *
         * @summary Health
         * @description Health check.
         * @see {@link https://openapi-qraft.github.io/openapi-qraft/docs/hooks/useQuery|`useQuery(...)` documentation}
         * @example Query without parameters
         * ```ts
         * const { data, isLoading } = qraft.agents.healthAgentsChatAgentHealthGet.useQuery()
         * ```
         */
        useQuery<TData = HealthAgentsChatAgentHealthGetData>(parameters: ServiceOperationQueryKey<HealthAgentsChatAgentHealthGetSchema, HealthAgentsChatAgentHealthGetParameters> | (DeepReadonly<HealthAgentsChatAgentHealthGetParameters> | void), options: Omit<DefinedInitialDataOptions<HealthAgentsChatAgentHealthGetData, HealthAgentsChatAgentHealthGetError, TData, ServiceOperationQueryKey<HealthAgentsChatAgentHealthGetSchema, HealthAgentsChatAgentHealthGetParameters>>, "queryKey">): DefinedUseQueryResult<TData, OperationError<HealthAgentsChatAgentHealthGetError>>;
        /**
         * @summary Health
         * @description Health check.
         */
        getInfiniteQueryKey(parameters: DeepReadonly<HealthAgentsChatAgentHealthGetParameters> | void): ServiceOperationInfiniteQueryKey<HealthAgentsChatAgentHealthGetSchema, HealthAgentsChatAgentHealthGetParameters>;
        /**
         * Performs asynchronous data fetching with support for infinite scrolling scenarios.
         * Manages paginated data and provides utilities for fetching additional pages.
         *
         * @summary Health
         * @description Health check.
         * @see {@link https://openapi-qraft.github.io/openapi-qraft/docs/hooks/useInfiniteQuery|`useInfiniteQuery(...)` documentation}
         *
         * @example Infinite Query
         * ```ts
         * const { data, isLoading, fetchNextPage } = qraft.agents.healthAgentsChatAgentHealthGet.useInfiniteQuery({}, {
         *     initialPageParam: {},
         *     getNextPageParam: (lastPage, allPages, lastPageParam, allPageParams) => getNextPageParams(lastPage)
         * })
         *
         * console.log(data);
         * fetchNextPage(); // Fetch the next page
         * ```
         */
        useInfiniteQuery<TPageParam extends HealthAgentsChatAgentHealthGetParameters, TQueryFnData = HealthAgentsChatAgentHealthGetData, TData = OperationInfiniteData<TQueryFnData, HealthAgentsChatAgentHealthGetParameters>>(parameters: ServiceOperationInfiniteQueryKey<HealthAgentsChatAgentHealthGetSchema, HealthAgentsChatAgentHealthGetParameters> | (DeepReadonly<HealthAgentsChatAgentHealthGetParameters> | void), options: Omit<UndefinedInitialDataInfiniteOptions<TQueryFnData, HealthAgentsChatAgentHealthGetError, TData, ServiceOperationInfiniteQueryKey<HealthAgentsChatAgentHealthGetSchema, HealthAgentsChatAgentHealthGetParameters>, PartialParameters<DeepReadonly<TPageParam>>>, "queryKey" | "getPreviousPageParam" | "getNextPageParam" | "initialPageParam"> & InfiniteQueryPageParamsOptions<TQueryFnData, PartialParameters<DeepReadonly<TPageParam>>>): UseInfiniteQueryResult<TData, OperationError<HealthAgentsChatAgentHealthGetError>>;
        /**
         * Performs asynchronous data fetching with support for infinite scrolling scenarios.
         * Manages paginated data and provides utilities for fetching additional pages.
         *
         * @summary Health
         * @description Health check.
         * @see {@link https://openapi-qraft.github.io/openapi-qraft/docs/hooks/useInfiniteQuery|`useInfiniteQuery(...)` documentation}
         *
         * @example Infinite Query
         * ```ts
         * const { data, isLoading, fetchNextPage } = qraft.agents.healthAgentsChatAgentHealthGet.useInfiniteQuery({}, {
         *     initialPageParam: {},
         *     getNextPageParam: (lastPage, allPages, lastPageParam, allPageParams) => getNextPageParams(lastPage)
         * })
         *
         * console.log(data);
         * fetchNextPage(); // Fetch the next page
         * ```
         */
        useInfiniteQuery<TPageParam extends HealthAgentsChatAgentHealthGetParameters, TQueryFnData = HealthAgentsChatAgentHealthGetData, TData = OperationInfiniteData<TQueryFnData, HealthAgentsChatAgentHealthGetParameters>>(parameters: ServiceOperationInfiniteQueryKey<HealthAgentsChatAgentHealthGetSchema, HealthAgentsChatAgentHealthGetParameters> | (DeepReadonly<HealthAgentsChatAgentHealthGetParameters> | void), options: Omit<DefinedInitialDataInfiniteOptions<TQueryFnData, HealthAgentsChatAgentHealthGetError, TData, ServiceOperationInfiniteQueryKey<HealthAgentsChatAgentHealthGetSchema, HealthAgentsChatAgentHealthGetParameters>, PartialParameters<DeepReadonly<TPageParam>>>, "queryKey" | "getPreviousPageParam" | "getNextPageParam" | "initialPageParam"> & InfiniteQueryPageParamsOptions<HealthAgentsChatAgentHealthGetData, PartialParameters<DeepReadonly<TPageParam>>>): DefinedUseInfiniteQueryResult<TData, OperationError<HealthAgentsChatAgentHealthGetError>>;
        /**
         * Monitors the number of queries currently fetching, matching the provided filters.
         * Useful for creating loading indicators or performing actions based on active requests.
         *
         * @summary Health
         * @description Health check.
         * @see {@link https://openapi-qraft.github.io/openapi-qraft/docs/hooks/useIsFetching|`useIsFetching(...)` documentation}
         * @example Checks the total number of queries fetching from the specified service method,
         * both normal and infinite. If no parameters are provided, no filtering is applied.
         * ```ts
         * const healthAgentsChatAgentHealthGetTotal = qraft.agents.healthAgentsChatAgentHealthGet.useIsFetching()
         * ```
         */
        useIsFetching<TInfinite extends boolean = false>(filters?: QueryFiltersByParameters<HealthAgentsChatAgentHealthGetSchema, HealthAgentsChatAgentHealthGetData, TInfinite, HealthAgentsChatAgentHealthGetParameters, HealthAgentsChatAgentHealthGetError> | QueryFiltersByQueryKey<HealthAgentsChatAgentHealthGetSchema, HealthAgentsChatAgentHealthGetData, TInfinite, HealthAgentsChatAgentHealthGetParameters, HealthAgentsChatAgentHealthGetError>): number;
        /**
         * Allows you to execute multiple asynchronous data fetching operations concurrently. This is especially useful for managing complex data dependencies in parallel.
         *
         * @summary Health
         * @description Health check.
         * @see {@link https://openapi-qraft.github.io/openapi-qraft/docs/hooks/useQueries|`useQueries(...)` documentation}
         * @example Multiple queries. Returns `data`, `error`, `isSuccess` and other properties.
         * ```ts
         * const healthAgentsChatAgentHealthGetResults = qraft.agents.healthAgentsChatAgentHealthGet.useQueries({
         *     queries: [
         *         {},
         *         {}
         *     ]
         * });
         * healthAgentsChatAgentHealthGetResults.forEach(({ isSuccess, data, error }) => console.log({ isSuccess, data, error }));
         * ```
         * @example Combined results. Only the data will be returned.
         * ```ts
         * const healthAgentsChatAgentHealthGetCombinedResults = qraft.agents.healthAgentsChatAgentHealthGet.useQueries({
         *     combine: results => results.map(result => result.data),
         *     queries: [
         *         {},
         *         {}
         *     ]
         * });
         * healthAgentsChatAgentHealthGetCombinedResults.forEach(data => console.log({ data }));
         * ```
         */
        useQueries<T extends Array<UseQueryOptionsForUseQueries<HealthAgentsChatAgentHealthGetSchema, HealthAgentsChatAgentHealthGetParameters, HealthAgentsChatAgentHealthGetData, HealthAgentsChatAgentHealthGetError>>, TCombinedResult = Array<UseQueryResult<HealthAgentsChatAgentHealthGetData, HealthAgentsChatAgentHealthGetError>>>(options: {
            queries: T;
            combine?: (results: Array<UseQueryResult<HealthAgentsChatAgentHealthGetData, HealthAgentsChatAgentHealthGetError>>) => TCombinedResult;
        }): TCombinedResult;
        /**
         * Performs asynchronous data fetching with Suspense support.
         * Similar to useQuery but integrates with React Suspense for loading states.
         *
         * @summary Health
         * @description Health check.
         * @see {@link https://openapi-qraft.github.io/openapi-qraft/docs/hooks/useSuspenseQuery|`useSuspenseQuery(...)` documentation}
         * @example Suspense Query without parameters
         * ```ts
         * const data = qraft.agents.healthAgentsChatAgentHealthGet.useSuspenseQuery()
         * ```
         */
        useSuspenseQuery<TData = HealthAgentsChatAgentHealthGetData>(parameters: ServiceOperationQueryKey<HealthAgentsChatAgentHealthGetSchema, HealthAgentsChatAgentHealthGetParameters> | (DeepReadonly<HealthAgentsChatAgentHealthGetParameters> | void), options?: Omit<UseSuspenseQueryOptions<HealthAgentsChatAgentHealthGetData, HealthAgentsChatAgentHealthGetError, TData, ServiceOperationQueryKey<HealthAgentsChatAgentHealthGetSchema, HealthAgentsChatAgentHealthGetParameters>>, "queryKey">): UseSuspenseQueryResult<TData, OperationError<HealthAgentsChatAgentHealthGetError>>;
        /**
         * Performs asynchronous data fetching with support for infinite scrolling scenarios.
         * Manages paginated data and provides utilities for fetching additional pages.
         * It functions similarly to `useInfiniteQuery`, but with added support for React Suspense.
         *
         * @summary Health
         * @description Health check.
         * @see {@link https://openapi-qraft.github.io/openapi-qraft/docs/hooks/useSuspenseInfiniteQuery|`useSuspenseInfiniteQuery(...)` documentation}
         *
         * @example Suspense Infinite Query
         * ```ts
         * const { data, isLoading, fetchNextPage } = qraft.agents.healthAgentsChatAgentHealthGet.useSuspenseInfiniteQuery({}, {
         *     initialPageParam: {},
         *     getNextPageParam: (lastPage, allPages, lastPageParam, allPageParams) => getNextPageParams(lastPage)
         * })
         *
         * console.log(data);
         * fetchNextPage(); // Fetch the next page
         * ```
         */
        useSuspenseInfiniteQuery<TPageParam extends HealthAgentsChatAgentHealthGetParameters, TData = HealthAgentsChatAgentHealthGetData>(parameters: ServiceOperationInfiniteQueryKey<HealthAgentsChatAgentHealthGetSchema, HealthAgentsChatAgentHealthGetParameters> | (DeepReadonly<HealthAgentsChatAgentHealthGetParameters> | void), options: Omit<UseSuspenseInfiniteQueryOptions<HealthAgentsChatAgentHealthGetData, HealthAgentsChatAgentHealthGetError, OperationInfiniteData<TData, HealthAgentsChatAgentHealthGetParameters>, ServiceOperationInfiniteQueryKey<HealthAgentsChatAgentHealthGetSchema, HealthAgentsChatAgentHealthGetParameters>, PartialParameters<DeepReadonly<TPageParam>>>, "queryKey" | "getPreviousPageParam" | "getNextPageParam" | "initialPageParam"> & InfiniteQueryPageParamsOptions<HealthAgentsChatAgentHealthGetData, PartialParameters<DeepReadonly<TPageParam>>>): UseSuspenseInfiniteQueryResult<OperationInfiniteData<TData, HealthAgentsChatAgentHealthGetParameters>, OperationError<HealthAgentsChatAgentHealthGetError>>;
        /**
         * Allows you to execute multiple asynchronous data fetching operations concurrently with Suspense support.
         * Similar to useQueries but integrates with React Suspense for loading states.
         *
         * @summary Health
         * @description Health check.
         * @see {@link https://openapi-qraft.github.io/openapi-qraft/docs/hooks/useSuspenseQueries|`useSuspenseQueries(...)` documentation}
         * @example Basic usage with Suspense
         * ```ts
         * const healthAgentsChatAgentHealthGetData = qraft.agents.healthAgentsChatAgentHealthGet.useSuspenseQueries({
         *     queries: [
         *         {},
         *         {}
         *     ]
         * });
         * healthAgentsChatAgentHealthGetResults.forEach(({ isSuccess, data, error }) => console.log({ isSuccess, data, error }));
         * ```
         * @example With data transformation using combine
         * ```ts
         * const healthAgentsChatAgentHealthGetCombinedData = qraft.agents.healthAgentsChatAgentHealthGet.useSuspenseQueries({
         *     combine: results => results.map(result => result.data),
         *     queries: [
         *         {},
         *         {}
         *     ]
         * });
         * healthAgentsChatAgentHealthGetCombinedData.forEach(data => console.log({ data }));
         * ```
         */
        useSuspenseQueries<T extends Array<UseQueryOptionsForUseSuspenseQuery<HealthAgentsChatAgentHealthGetSchema, HealthAgentsChatAgentHealthGetParameters, HealthAgentsChatAgentHealthGetData, HealthAgentsChatAgentHealthGetError>>, TCombinedResult = Array<UseSuspenseQueryResult<HealthAgentsChatAgentHealthGetData, HealthAgentsChatAgentHealthGetError>>>(options: {
            queries: T;
            combine?: (results: Array<WithOptional<UseSuspenseQueryResult<HealthAgentsChatAgentHealthGetData, HealthAgentsChatAgentHealthGetError>, "data">>) => TCombinedResult;
        }): TCombinedResult;
        /**
         * @summary Health
         * @description Health check.
         */
        fetchQuery(options: ServiceOperationFetchQueryOptions<HealthAgentsChatAgentHealthGetSchema, HealthAgentsChatAgentHealthGetData, HealthAgentsChatAgentHealthGetParameters, HealthAgentsChatAgentHealthGetError> | void): Promise<HealthAgentsChatAgentHealthGetData>;
        /**
         * @summary Health
         * @description Health check.
         */
        prefetchQuery(options: ServiceOperationFetchQueryOptions<HealthAgentsChatAgentHealthGetSchema, HealthAgentsChatAgentHealthGetData, HealthAgentsChatAgentHealthGetParameters, HealthAgentsChatAgentHealthGetError> | void): Promise<void>;
        /**
         * @summary Health
         * @description Health check.
         */
        ensureQueryData(options: ServiceOperationEnsureQueryDataOptions<HealthAgentsChatAgentHealthGetSchema, HealthAgentsChatAgentHealthGetData, HealthAgentsChatAgentHealthGetParameters, HealthAgentsChatAgentHealthGetError> | void): Promise<HealthAgentsChatAgentHealthGetData>;
        /**
         * @summary Health
         * @description Health check.
         */
        fetchInfiniteQuery<TPageParam extends HealthAgentsChatAgentHealthGetParameters>(options: ServiceOperationFetchInfiniteQueryOptions<HealthAgentsChatAgentHealthGetSchema, HealthAgentsChatAgentHealthGetData, HealthAgentsChatAgentHealthGetParameters, DeepReadonly<TPageParam>, HealthAgentsChatAgentHealthGetError> | void): Promise<OperationInfiniteData<HealthAgentsChatAgentHealthGetData, HealthAgentsChatAgentHealthGetParameters>>;
        /**
         * @summary Health
         * @description Health check.
         */
        prefetchInfiniteQuery<TPageParam extends HealthAgentsChatAgentHealthGetParameters>(options: ServiceOperationFetchInfiniteQueryOptions<HealthAgentsChatAgentHealthGetSchema, HealthAgentsChatAgentHealthGetData, HealthAgentsChatAgentHealthGetParameters, DeepReadonly<TPageParam>, HealthAgentsChatAgentHealthGetError> | void): Promise<void>;
        /**
         * @summary Health
         * @description Health check.
         */
        ensureInfiniteQueryData<TPageParam extends HealthAgentsChatAgentHealthGetParameters>(options: ServiceOperationEnsureInfiniteQueryDataOptions<HealthAgentsChatAgentHealthGetSchema, HealthAgentsChatAgentHealthGetData, HealthAgentsChatAgentHealthGetParameters, DeepReadonly<TPageParam>, HealthAgentsChatAgentHealthGetError> | void): Promise<OperationInfiniteData<HealthAgentsChatAgentHealthGetData, HealthAgentsChatAgentHealthGetParameters>>;
        /**
         * @summary Health
         * @description Health check.
         */
        getQueryData(parameters: ServiceOperationQueryKey<HealthAgentsChatAgentHealthGetSchema, HealthAgentsChatAgentHealthGetParameters> | (DeepReadonly<HealthAgentsChatAgentHealthGetParameters> | void)): HealthAgentsChatAgentHealthGetData | undefined;
        /**
         * @summary Health
         * @description Health check.
         */
        getInfiniteQueryData(parameters: ServiceOperationInfiniteQueryKey<HealthAgentsChatAgentHealthGetSchema, HealthAgentsChatAgentHealthGetParameters> | (DeepReadonly<HealthAgentsChatAgentHealthGetParameters> | void)): OperationInfiniteData<HealthAgentsChatAgentHealthGetData, HealthAgentsChatAgentHealthGetParameters> | undefined;
        /**
         * @summary Health
         * @description Health check.
         */
        getQueriesData<TInfinite extends boolean = false>(filters?: QueryFiltersByParameters<HealthAgentsChatAgentHealthGetSchema, HealthAgentsChatAgentHealthGetData, TInfinite, HealthAgentsChatAgentHealthGetParameters, HealthAgentsChatAgentHealthGetError> | QueryFiltersByQueryKey<HealthAgentsChatAgentHealthGetSchema, HealthAgentsChatAgentHealthGetData, TInfinite, HealthAgentsChatAgentHealthGetParameters, HealthAgentsChatAgentHealthGetError>): TInfinite extends true ? Array<[
            queryKey: ServiceOperationInfiniteQueryKey<HealthAgentsChatAgentHealthGetSchema, HealthAgentsChatAgentHealthGetParameters>,
            data: NoInfer<OperationInfiniteData<HealthAgentsChatAgentHealthGetData, HealthAgentsChatAgentHealthGetParameters>> | undefined
        ]> : Array<[
            queryKey: ServiceOperationQueryKey<HealthAgentsChatAgentHealthGetSchema, HealthAgentsChatAgentHealthGetParameters>,
            data: HealthAgentsChatAgentHealthGetData | undefined
        ]>;
        /**
         * @summary Health
         * @description Health check.
         */
        getQueryState(parameters: ServiceOperationQueryKey<HealthAgentsChatAgentHealthGetSchema, HealthAgentsChatAgentHealthGetParameters> | (DeepReadonly<HealthAgentsChatAgentHealthGetParameters> | void)): QueryState<HealthAgentsChatAgentHealthGetData, HealthAgentsChatAgentHealthGetError> | undefined;
        /**
         * @summary Health
         * @description Health check.
         */
        getInfiniteQueryState(parameters: DeepReadonly<HealthAgentsChatAgentHealthGetParameters> | ServiceOperationInfiniteQueryKey<HealthAgentsChatAgentHealthGetSchema, HealthAgentsChatAgentHealthGetParameters> | void): QueryState<OperationInfiniteData<HealthAgentsChatAgentHealthGetData, HealthAgentsChatAgentHealthGetParameters>, HealthAgentsChatAgentHealthGetError> | undefined;
        /**
         * @summary Health
         * @description Health check.
         */
        setQueryData(parameters: (DeepReadonly<HealthAgentsChatAgentHealthGetParameters> | undefined) | ServiceOperationQueryKey<HealthAgentsChatAgentHealthGetSchema, HealthAgentsChatAgentHealthGetParameters>, updater: Updater<NoInfer<HealthAgentsChatAgentHealthGetData> | undefined, NoInfer<DeepReadonly<HealthAgentsChatAgentHealthGetData>> | undefined>, options?: SetDataOptions): HealthAgentsChatAgentHealthGetData | undefined;
        /**
         * @summary Health
         * @description Health check.
         */
        setInfiniteQueryData(parameters: (DeepReadonly<HealthAgentsChatAgentHealthGetParameters> | undefined) | ServiceOperationInfiniteQueryKey<HealthAgentsChatAgentHealthGetSchema, HealthAgentsChatAgentHealthGetParameters>, updater: Updater<NoInfer<OperationInfiniteData<HealthAgentsChatAgentHealthGetData, HealthAgentsChatAgentHealthGetParameters>> | undefined, NoInfer<DeepReadonly<OperationInfiniteData<HealthAgentsChatAgentHealthGetData, HealthAgentsChatAgentHealthGetParameters>>> | undefined>, options?: SetDataOptions): OperationInfiniteData<HealthAgentsChatAgentHealthGetData, HealthAgentsChatAgentHealthGetParameters> | undefined;
        /**
         * @summary Health
         * @description Health check.
         */
        setQueriesData<TInfinite extends boolean = false>(filters: QueryFiltersByParameters<HealthAgentsChatAgentHealthGetSchema, HealthAgentsChatAgentHealthGetData, TInfinite, HealthAgentsChatAgentHealthGetParameters, HealthAgentsChatAgentHealthGetError> | QueryFiltersByQueryKey<HealthAgentsChatAgentHealthGetSchema, HealthAgentsChatAgentHealthGetData, TInfinite, HealthAgentsChatAgentHealthGetParameters, HealthAgentsChatAgentHealthGetError>, updater: Updater<NoInfer<HealthAgentsChatAgentHealthGetData> | undefined, NoInfer<HealthAgentsChatAgentHealthGetData> | undefined>, options?: SetDataOptions): Array<HealthAgentsChatAgentHealthGetData | undefined>;
        /**
         * @summary Health
         * @description Health check.
         */
        invalidateQueries<TInfinite extends boolean = false>(filters?: InvalidateQueryFilters<HealthAgentsChatAgentHealthGetSchema, HealthAgentsChatAgentHealthGetData, TInfinite, HealthAgentsChatAgentHealthGetParameters, HealthAgentsChatAgentHealthGetError>, options?: InvalidateOptions): Promise<void>;
        /**
         * @summary Health
         * @description Health check.
         */
        refetchQueries<TInfinite extends boolean = false>(filters?: QueryFiltersByParameters<HealthAgentsChatAgentHealthGetSchema, HealthAgentsChatAgentHealthGetData, TInfinite, HealthAgentsChatAgentHealthGetParameters, HealthAgentsChatAgentHealthGetError> | QueryFiltersByQueryKey<HealthAgentsChatAgentHealthGetSchema, HealthAgentsChatAgentHealthGetData, TInfinite, HealthAgentsChatAgentHealthGetParameters, HealthAgentsChatAgentHealthGetError>, options?: RefetchOptions): Promise<void>;
        /**
         * @summary Health
         * @description Health check.
         */
        cancelQueries<TInfinite extends boolean = false>(filters?: QueryFiltersByParameters<HealthAgentsChatAgentHealthGetSchema, HealthAgentsChatAgentHealthGetData, TInfinite, HealthAgentsChatAgentHealthGetParameters, HealthAgentsChatAgentHealthGetError> | QueryFiltersByQueryKey<HealthAgentsChatAgentHealthGetSchema, HealthAgentsChatAgentHealthGetData, TInfinite, HealthAgentsChatAgentHealthGetParameters, HealthAgentsChatAgentHealthGetError>, options?: CancelOptions): Promise<void>;
        /**
         * @summary Health
         * @description Health check.
         */
        removeQueries<TInfinite extends boolean = false>(filters?: QueryFiltersByParameters<HealthAgentsChatAgentHealthGetSchema, HealthAgentsChatAgentHealthGetData, TInfinite, HealthAgentsChatAgentHealthGetParameters, HealthAgentsChatAgentHealthGetError> | QueryFiltersByQueryKey<HealthAgentsChatAgentHealthGetSchema, HealthAgentsChatAgentHealthGetData, TInfinite, HealthAgentsChatAgentHealthGetParameters, HealthAgentsChatAgentHealthGetError>): void;
        /**
         * @summary Health
         * @description Health check.
         */
        resetQueries<TInfinite extends boolean = false>(filters?: QueryFiltersByParameters<HealthAgentsChatAgentHealthGetSchema, HealthAgentsChatAgentHealthGetData, TInfinite, HealthAgentsChatAgentHealthGetParameters, HealthAgentsChatAgentHealthGetError> | QueryFiltersByQueryKey<HealthAgentsChatAgentHealthGetSchema, HealthAgentsChatAgentHealthGetData, TInfinite, HealthAgentsChatAgentHealthGetParameters, HealthAgentsChatAgentHealthGetError>, options?: ResetOptions): Promise<void>;
        /**
         * @summary Health
         * @description Health check.
         */
        isFetching<TInfinite extends boolean = false>(filters?: QueryFiltersByParameters<HealthAgentsChatAgentHealthGetSchema, HealthAgentsChatAgentHealthGetData, TInfinite, HealthAgentsChatAgentHealthGetParameters, HealthAgentsChatAgentHealthGetError> | QueryFiltersByQueryKey<HealthAgentsChatAgentHealthGetSchema, HealthAgentsChatAgentHealthGetData, TInfinite, HealthAgentsChatAgentHealthGetParameters, HealthAgentsChatAgentHealthGetError>): number;
        schema: HealthAgentsChatAgentHealthGetSchema;
        types: {
            parameters: HealthAgentsChatAgentHealthGetParameters;
            data: HealthAgentsChatAgentHealthGetData;
            error: HealthAgentsChatAgentHealthGetError;
        };
    };
}
/** @summary Langgraph Agent Endpoint */
export const langgraphAgentEndpointAgentsChatAgentPost = {
    schema: {
        method: "post",
        url: "/agents/chat-agent",
        mediaType: ["application/json"]
    }
} as {
    schema: LanggraphAgentEndpointAgentsChatAgentPostSchema;
    [QraftServiceOperationsToken]: AgentsService["langgraphAgentEndpointAgentsChatAgentPost"];
};
/**
 * @summary Health
 * @description Health check.
 */
export const healthAgentsChatAgentHealthGet = {
    schema: {
        method: "get",
        url: "/agents/chat-agent/health"
    }
} as {
    schema: HealthAgentsChatAgentHealthGetSchema;
    [QraftServiceOperationsToken]: AgentsService["healthAgentsChatAgentHealthGet"];
};
export const agentsService = {
    langgraphAgentEndpointAgentsChatAgentPost,
    healthAgentsChatAgentHealthGet
} as const;
type LanggraphAgentEndpointAgentsChatAgentPostSchema = {
    method: "post";
    url: "/agents/chat-agent";
    mediaType: [
        "application/json"
    ];
};
type LanggraphAgentEndpointAgentsChatAgentPostParameters = {
    query?: never;
    header?: never;
    path?: never;
};
type LanggraphAgentEndpointAgentsChatAgentPostData = paths["/agents/chat-agent"]["post"]["responses"]["200"]["content"]["application/json"];
type LanggraphAgentEndpointAgentsChatAgentPostError = paths["/agents/chat-agent"]["post"]["responses"]["422"]["content"]["application/json"];
type LanggraphAgentEndpointAgentsChatAgentPostBody = paths["/agents/chat-agent"]["post"]["requestBody"]["content"]["application/json"];
type HealthAgentsChatAgentHealthGetSchema = {
    method: "get";
    url: "/agents/chat-agent/health";
};
type HealthAgentsChatAgentHealthGetParameters = undefined;
type HealthAgentsChatAgentHealthGetData = paths["/agents/chat-agent/health"]["get"]["responses"]["200"]["content"]["application/json"];
type HealthAgentsChatAgentHealthGetError = unknown;
