/**
 * This file was auto-generated by @openapi-qraft/cli.
 * Do not make direct changes to the file.
 */

import type { ConversationsService } from "./ConversationsService";
import { conversationsService } from "./ConversationsService";
import type { DocumentsService } from "./DocumentsService";
import { documentsService } from "./DocumentsService";
import type { IngestionJobsService } from "./IngestionJobsService";
import { ingestionJobsService } from "./IngestionJobsService";
import type { AgentsService } from "./AgentsService";
import { agentsService } from "./AgentsService";
export type Services = {
    conversations: ConversationsService;
    documents: DocumentsService;
    ingestionJobs: IngestionJobsService;
    agents: AgentsService;
};
export const services: {
    conversations: typeof conversationsService;
    documents: typeof documentsService;
    ingestionJobs: typeof ingestionJobsService;
    agents: typeof agentsService;
} = {
    conversations: conversationsService,
    documents: documentsService,
    ingestionJobs: ingestionJobsService,
    agents: agentsService
};
