/**
 * This file was auto-generated by @openapi-qraft/cli.
 * Do not make direct changes to the file.
 */

import type { paths } from "../schema";
import type { DeepReadonly, InvalidateQueryFilters, OperationError, OperationInfiniteData, PartialParameters, QueryFiltersByParameters, QueryFiltersByQueryKey, QueryFnOptionsByParameters, QueryFnOptionsByQueryKey, RequestFnResponse, ServiceOperationEnsureInfiniteQueryDataOptions, ServiceOperationEnsureQueryDataOptions, ServiceOperationFetchInfiniteQueryOptions, ServiceOperationFetchQueryOptions, ServiceOperationInfiniteQueryKey, ServiceOperationQueryKey, UseQueryOptionsForUseQueries, UseQueryOptionsForUseSuspenseQuery, WithOptional, QraftServiceOperationsToken } from "@openapi-qraft/tanstack-query-react-types";
import type { CancelOptions, DefinedInitialDataInfiniteOptions, DefinedInitialDataOptions, DefinedUseInfiniteQueryResult, DefinedUseQueryResult, InfiniteQueryPageParamsOptions, InvalidateOptions, NoInfer, QueryState, RefetchOptions, ResetOptions, SetDataOptions, UndefinedInitialDataInfiniteOptions, UndefinedInitialDataOptions, Updater, UseInfiniteQueryResult, UseQueryResult, UseSuspenseInfiniteQueryOptions, UseSuspenseInfiniteQueryResult, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
export interface IngestionJobsService {
    /** @summary Get Ingestion Job */
    getIngestionJob: {
        /** @summary Get Ingestion Job */
        <TMeta extends Record<string, any>, TSignal extends AbortSignal = AbortSignal>(options: QueryFnOptionsByQueryKey<GetIngestionJobSchema, GetIngestionJobParameters, TMeta, TSignal> | (QueryFnOptionsByParameters<GetIngestionJobParameters, TMeta, TSignal>), client?: (schema: GetIngestionJobSchema, options: {
            parameters: GetIngestionJobParameters;
            signal?: TSignal;
            meta?: TMeta;
        }) => Promise<RequestFnResponse<GetIngestionJobData, GetIngestionJobError>>): Promise<RequestFnResponse<GetIngestionJobData, GetIngestionJobError>>;
        /** @summary Get Ingestion Job */
        getQueryKey(parameters: DeepReadonly<GetIngestionJobParameters>): ServiceOperationQueryKey<GetIngestionJobSchema, GetIngestionJobParameters>;
        /**
         * Performs asynchronous data fetching, manages loading states and error handling.
         *
         * @summary Get Ingestion Job
         * @see {@link https://openapi-qraft.github.io/openapi-qraft/docs/hooks/useQuery|`useQuery(...)` documentation}
         * @example Query with parameters
         * ```ts
         * const { data, isLoading } = qraft.ingestionJobs.getIngestionJob.useQuery({
         *     path: {
         *         job_id: jobId
         *     }
         * })
         * ```
         */
        useQuery<TData = GetIngestionJobData>(parameters: ServiceOperationQueryKey<GetIngestionJobSchema, GetIngestionJobParameters> | (DeepReadonly<GetIngestionJobParameters>), options?: Omit<UndefinedInitialDataOptions<GetIngestionJobData, GetIngestionJobError, TData, ServiceOperationQueryKey<GetIngestionJobSchema, GetIngestionJobParameters>>, "queryKey">): UseQueryResult<TData, OperationError<GetIngestionJobError>>;
        /**
         * Performs asynchronous data fetching, manages loading states and error handling.
         *
         * @summary Get Ingestion Job
         * @see {@link https://openapi-qraft.github.io/openapi-qraft/docs/hooks/useQuery|`useQuery(...)` documentation}
         * @example Query with parameters
         * ```ts
         * const { data, isLoading } = qraft.ingestionJobs.getIngestionJob.useQuery({
         *     path: {
         *         job_id: jobId
         *     }
         * })
         * ```
         */
        useQuery<TData = GetIngestionJobData>(parameters: ServiceOperationQueryKey<GetIngestionJobSchema, GetIngestionJobParameters> | (DeepReadonly<GetIngestionJobParameters>), options: Omit<DefinedInitialDataOptions<GetIngestionJobData, GetIngestionJobError, TData, ServiceOperationQueryKey<GetIngestionJobSchema, GetIngestionJobParameters>>, "queryKey">): DefinedUseQueryResult<TData, OperationError<GetIngestionJobError>>;
        /** @summary Get Ingestion Job */
        getInfiniteQueryKey(parameters: DeepReadonly<GetIngestionJobParameters>): ServiceOperationInfiniteQueryKey<GetIngestionJobSchema, GetIngestionJobParameters>;
        /**
         * Performs asynchronous data fetching with support for infinite scrolling scenarios.
         * Manages paginated data and provides utilities for fetching additional pages.
         *
         * @summary Get Ingestion Job
         * @see {@link https://openapi-qraft.github.io/openapi-qraft/docs/hooks/useInfiniteQuery|`useInfiniteQuery(...)` documentation}
         *
         * @example Infinite Query
         * ```ts
         * const { data, isLoading, fetchNextPage } = qraft.ingestionJobs.getIngestionJob.useInfiniteQuery({
         *     path: {
         *         job_id: jobId
         *     }
         * }, {
         *     initialPageParam: {},
         *     getNextPageParam: (lastPage, allPages, lastPageParam, allPageParams) => getNextPageParams(lastPage)
         * })
         *
         * console.log(data);
         * fetchNextPage(); // Fetch the next page
         * ```
         */
        useInfiniteQuery<TPageParam extends GetIngestionJobParameters, TQueryFnData = GetIngestionJobData, TData = OperationInfiniteData<TQueryFnData, GetIngestionJobParameters>>(parameters: ServiceOperationInfiniteQueryKey<GetIngestionJobSchema, GetIngestionJobParameters> | (DeepReadonly<GetIngestionJobParameters>), options: Omit<UndefinedInitialDataInfiniteOptions<TQueryFnData, GetIngestionJobError, TData, ServiceOperationInfiniteQueryKey<GetIngestionJobSchema, GetIngestionJobParameters>, PartialParameters<DeepReadonly<TPageParam>>>, "queryKey" | "getPreviousPageParam" | "getNextPageParam" | "initialPageParam"> & InfiniteQueryPageParamsOptions<TQueryFnData, PartialParameters<DeepReadonly<TPageParam>>>): UseInfiniteQueryResult<TData, OperationError<GetIngestionJobError>>;
        /**
         * Performs asynchronous data fetching with support for infinite scrolling scenarios.
         * Manages paginated data and provides utilities for fetching additional pages.
         *
         * @summary Get Ingestion Job
         * @see {@link https://openapi-qraft.github.io/openapi-qraft/docs/hooks/useInfiniteQuery|`useInfiniteQuery(...)` documentation}
         *
         * @example Infinite Query
         * ```ts
         * const { data, isLoading, fetchNextPage } = qraft.ingestionJobs.getIngestionJob.useInfiniteQuery({
         *     path: {
         *         job_id: jobId
         *     }
         * }, {
         *     initialPageParam: {},
         *     getNextPageParam: (lastPage, allPages, lastPageParam, allPageParams) => getNextPageParams(lastPage)
         * })
         *
         * console.log(data);
         * fetchNextPage(); // Fetch the next page
         * ```
         */
        useInfiniteQuery<TPageParam extends GetIngestionJobParameters, TQueryFnData = GetIngestionJobData, TData = OperationInfiniteData<TQueryFnData, GetIngestionJobParameters>>(parameters: ServiceOperationInfiniteQueryKey<GetIngestionJobSchema, GetIngestionJobParameters> | (DeepReadonly<GetIngestionJobParameters>), options: Omit<DefinedInitialDataInfiniteOptions<TQueryFnData, GetIngestionJobError, TData, ServiceOperationInfiniteQueryKey<GetIngestionJobSchema, GetIngestionJobParameters>, PartialParameters<DeepReadonly<TPageParam>>>, "queryKey" | "getPreviousPageParam" | "getNextPageParam" | "initialPageParam"> & InfiniteQueryPageParamsOptions<GetIngestionJobData, PartialParameters<DeepReadonly<TPageParam>>>): DefinedUseInfiniteQueryResult<TData, OperationError<GetIngestionJobError>>;
        /**
         * Monitors the number of queries currently fetching, matching the provided filters.
         * Useful for creating loading indicators or performing actions based on active requests.
         *
         * @summary Get Ingestion Job
         * @see {@link https://openapi-qraft.github.io/openapi-qraft/docs/hooks/useIsFetching|`useIsFetching(...)` documentation}
         * @example Checks the total number of queries fetching from the specified service method,
         * both normal and infinite. If no parameters are provided, no filtering is applied.
         * ```ts
         * const getIngestionJobTotal = qraft.ingestionJobs.getIngestionJob.useIsFetching()
         * ```
         * @example Checks the number of normal queries fetching with the specified parameters.
         * ```ts
         * const getIngestionJobByParametersTotal = qraft.ingestionJobs.getIngestionJob.useIsFetching({
         *     infinite: false,
         *     parameters: {
         *         path: {
         *             job_id: jobId
         *         }
         *     }
         * })
         * ```
         */
        useIsFetching<TInfinite extends boolean = false>(filters?: QueryFiltersByParameters<GetIngestionJobSchema, GetIngestionJobData, TInfinite, GetIngestionJobParameters, GetIngestionJobError> | QueryFiltersByQueryKey<GetIngestionJobSchema, GetIngestionJobData, TInfinite, GetIngestionJobParameters, GetIngestionJobError>): number;
        /**
         * Allows you to execute multiple asynchronous data fetching operations concurrently. This is especially useful for managing complex data dependencies in parallel.
         *
         * @summary Get Ingestion Job
         * @see {@link https://openapi-qraft.github.io/openapi-qraft/docs/hooks/useQueries|`useQueries(...)` documentation}
         * @example Multiple queries. Returns `data`, `error`, `isSuccess` and other properties.
         * ```ts
         * const getIngestionJobResults = qraft.ingestionJobs.getIngestionJob.useQueries({
         *     queries: [
         *         {
         *             path: {
         *                 job_id: jobId1
         *             }
         *         },
         *         {
         *             path: {
         *                 job_id: jobId2
         *             }
         *         }
         *     ]
         * });
         * getIngestionJobResults.forEach(({ isSuccess, data, error }) => console.log({ isSuccess, data, error }));
         * ```
         * @example Combined results. Only the data will be returned.
         * ```ts
         * const getIngestionJobCombinedResults = qraft.ingestionJobs.getIngestionJob.useQueries({
         *     combine: results => results.map(result => result.data),
         *     queries: [
         *         {
         *             path: {
         *                 job_id: jobId1
         *             }
         *         },
         *         {
         *             path: {
         *                 job_id: jobId2
         *             }
         *         }
         *     ]
         * });
         * getIngestionJobCombinedResults.forEach(data => console.log({ data }));
         * ```
         */
        useQueries<T extends Array<UseQueryOptionsForUseQueries<GetIngestionJobSchema, GetIngestionJobParameters, GetIngestionJobData, GetIngestionJobError>>, TCombinedResult = Array<UseQueryResult<GetIngestionJobData, GetIngestionJobError>>>(options: {
            queries: T;
            combine?: (results: Array<UseQueryResult<GetIngestionJobData, GetIngestionJobError>>) => TCombinedResult;
        }): TCombinedResult;
        /**
         * Performs asynchronous data fetching with Suspense support.
         * Similar to useQuery but integrates with React Suspense for loading states.
         *
         * @summary Get Ingestion Job
         * @see {@link https://openapi-qraft.github.io/openapi-qraft/docs/hooks/useSuspenseQuery|`useSuspenseQuery(...)` documentation}
         * @example Suspense Query with parameters
         * ```ts
         * const data = qraft.ingestionJobs.getIngestionJob.useSuspenseQuery({
         *     path: {
         *         job_id: jobId
         *     }
         * })
         * ```
         */
        useSuspenseQuery<TData = GetIngestionJobData>(parameters: ServiceOperationQueryKey<GetIngestionJobSchema, GetIngestionJobParameters> | (DeepReadonly<GetIngestionJobParameters>), options?: Omit<UseSuspenseQueryOptions<GetIngestionJobData, GetIngestionJobError, TData, ServiceOperationQueryKey<GetIngestionJobSchema, GetIngestionJobParameters>>, "queryKey">): UseSuspenseQueryResult<TData, OperationError<GetIngestionJobError>>;
        /**
         * Performs asynchronous data fetching with support for infinite scrolling scenarios.
         * Manages paginated data and provides utilities for fetching additional pages.
         * It functions similarly to `useInfiniteQuery`, but with added support for React Suspense.
         *
         * @summary Get Ingestion Job
         * @see {@link https://openapi-qraft.github.io/openapi-qraft/docs/hooks/useSuspenseInfiniteQuery|`useSuspenseInfiniteQuery(...)` documentation}
         *
         * @example Suspense Infinite Query
         * ```ts
         * const { data, isLoading, fetchNextPage } = qraft.ingestionJobs.getIngestionJob.useSuspenseInfiniteQuery({
         *     path: {
         *         job_id: jobId
         *     }
         * }, {
         *     initialPageParam: {},
         *     getNextPageParam: (lastPage, allPages, lastPageParam, allPageParams) => getNextPageParams(lastPage)
         * })
         *
         * console.log(data);
         * fetchNextPage(); // Fetch the next page
         * ```
         */
        useSuspenseInfiniteQuery<TPageParam extends GetIngestionJobParameters, TData = GetIngestionJobData>(parameters: ServiceOperationInfiniteQueryKey<GetIngestionJobSchema, GetIngestionJobParameters> | (DeepReadonly<GetIngestionJobParameters>), options: Omit<UseSuspenseInfiniteQueryOptions<GetIngestionJobData, GetIngestionJobError, OperationInfiniteData<TData, GetIngestionJobParameters>, ServiceOperationInfiniteQueryKey<GetIngestionJobSchema, GetIngestionJobParameters>, PartialParameters<DeepReadonly<TPageParam>>>, "queryKey" | "getPreviousPageParam" | "getNextPageParam" | "initialPageParam"> & InfiniteQueryPageParamsOptions<GetIngestionJobData, PartialParameters<DeepReadonly<TPageParam>>>): UseSuspenseInfiniteQueryResult<OperationInfiniteData<TData, GetIngestionJobParameters>, OperationError<GetIngestionJobError>>;
        /**
         * Allows you to execute multiple asynchronous data fetching operations concurrently with Suspense support.
         * Similar to useQueries but integrates with React Suspense for loading states.
         *
         * @summary Get Ingestion Job
         * @see {@link https://openapi-qraft.github.io/openapi-qraft/docs/hooks/useSuspenseQueries|`useSuspenseQueries(...)` documentation}
         * @example Basic usage with Suspense
         * ```ts
         * const getIngestionJobData = qraft.ingestionJobs.getIngestionJob.useSuspenseQueries({
         *     queries: [
         *         {
         *             path: {
         *                 job_id: jobId1
         *             }
         *         },
         *         {
         *             path: {
         *                 job_id: jobId2
         *             }
         *         }
         *     ]
         * });
         * getIngestionJobResults.forEach(({ isSuccess, data, error }) => console.log({ isSuccess, data, error }));
         * ```
         * @example With data transformation using combine
         * ```ts
         * const getIngestionJobCombinedData = qraft.ingestionJobs.getIngestionJob.useSuspenseQueries({
         *     combine: results => results.map(result => result.data),
         *     queries: [
         *         {
         *             path: {
         *                 job_id: jobId1
         *             }
         *         },
         *         {
         *             path: {
         *                 job_id: jobId2
         *             }
         *         }
         *     ]
         * });
         * getIngestionJobCombinedData.forEach(data => console.log({ data }));
         * ```
         */
        useSuspenseQueries<T extends Array<UseQueryOptionsForUseSuspenseQuery<GetIngestionJobSchema, GetIngestionJobParameters, GetIngestionJobData, GetIngestionJobError>>, TCombinedResult = Array<UseSuspenseQueryResult<GetIngestionJobData, GetIngestionJobError>>>(options: {
            queries: T;
            combine?: (results: Array<WithOptional<UseSuspenseQueryResult<GetIngestionJobData, GetIngestionJobError>, "data">>) => TCombinedResult;
        }): TCombinedResult;
        /** @summary Get Ingestion Job */
        fetchQuery(options: ServiceOperationFetchQueryOptions<GetIngestionJobSchema, GetIngestionJobData, GetIngestionJobParameters, GetIngestionJobError>): Promise<GetIngestionJobData>;
        /** @summary Get Ingestion Job */
        prefetchQuery(options: ServiceOperationFetchQueryOptions<GetIngestionJobSchema, GetIngestionJobData, GetIngestionJobParameters, GetIngestionJobError>): Promise<void>;
        /** @summary Get Ingestion Job */
        ensureQueryData(options: ServiceOperationEnsureQueryDataOptions<GetIngestionJobSchema, GetIngestionJobData, GetIngestionJobParameters, GetIngestionJobError>): Promise<GetIngestionJobData>;
        /** @summary Get Ingestion Job */
        fetchInfiniteQuery<TPageParam extends GetIngestionJobParameters>(options: ServiceOperationFetchInfiniteQueryOptions<GetIngestionJobSchema, GetIngestionJobData, GetIngestionJobParameters, DeepReadonly<TPageParam>, GetIngestionJobError>): Promise<OperationInfiniteData<GetIngestionJobData, GetIngestionJobParameters>>;
        /** @summary Get Ingestion Job */
        prefetchInfiniteQuery<TPageParam extends GetIngestionJobParameters>(options: ServiceOperationFetchInfiniteQueryOptions<GetIngestionJobSchema, GetIngestionJobData, GetIngestionJobParameters, DeepReadonly<TPageParam>, GetIngestionJobError>): Promise<void>;
        /** @summary Get Ingestion Job */
        ensureInfiniteQueryData<TPageParam extends GetIngestionJobParameters>(options: ServiceOperationEnsureInfiniteQueryDataOptions<GetIngestionJobSchema, GetIngestionJobData, GetIngestionJobParameters, DeepReadonly<TPageParam>, GetIngestionJobError>): Promise<OperationInfiniteData<GetIngestionJobData, GetIngestionJobParameters>>;
        /** @summary Get Ingestion Job */
        getQueryData(parameters: ServiceOperationQueryKey<GetIngestionJobSchema, GetIngestionJobParameters> | (DeepReadonly<GetIngestionJobParameters>)): GetIngestionJobData | undefined;
        /** @summary Get Ingestion Job */
        getInfiniteQueryData(parameters: ServiceOperationInfiniteQueryKey<GetIngestionJobSchema, GetIngestionJobParameters> | (DeepReadonly<GetIngestionJobParameters>)): OperationInfiniteData<GetIngestionJobData, GetIngestionJobParameters> | undefined;
        /** @summary Get Ingestion Job */
        getQueriesData<TInfinite extends boolean = false>(filters?: QueryFiltersByParameters<GetIngestionJobSchema, GetIngestionJobData, TInfinite, GetIngestionJobParameters, GetIngestionJobError> | QueryFiltersByQueryKey<GetIngestionJobSchema, GetIngestionJobData, TInfinite, GetIngestionJobParameters, GetIngestionJobError>): TInfinite extends true ? Array<[
            queryKey: ServiceOperationInfiniteQueryKey<GetIngestionJobSchema, GetIngestionJobParameters>,
            data: NoInfer<OperationInfiniteData<GetIngestionJobData, GetIngestionJobParameters>> | undefined
        ]> : Array<[
            queryKey: ServiceOperationQueryKey<GetIngestionJobSchema, GetIngestionJobParameters>,
            data: GetIngestionJobData | undefined
        ]>;
        /** @summary Get Ingestion Job */
        getQueryState(parameters: ServiceOperationQueryKey<GetIngestionJobSchema, GetIngestionJobParameters> | (DeepReadonly<GetIngestionJobParameters>)): QueryState<GetIngestionJobData, GetIngestionJobError> | undefined;
        /** @summary Get Ingestion Job */
        getInfiniteQueryState(parameters: DeepReadonly<GetIngestionJobParameters> | ServiceOperationInfiniteQueryKey<GetIngestionJobSchema, GetIngestionJobParameters>): QueryState<OperationInfiniteData<GetIngestionJobData, GetIngestionJobParameters>, GetIngestionJobError> | undefined;
        /** @summary Get Ingestion Job */
        setQueryData(parameters: (DeepReadonly<GetIngestionJobParameters>) | ServiceOperationQueryKey<GetIngestionJobSchema, GetIngestionJobParameters>, updater: Updater<NoInfer<GetIngestionJobData> | undefined, NoInfer<DeepReadonly<GetIngestionJobData>> | undefined>, options?: SetDataOptions): GetIngestionJobData | undefined;
        /** @summary Get Ingestion Job */
        setInfiniteQueryData(parameters: (DeepReadonly<GetIngestionJobParameters>) | ServiceOperationInfiniteQueryKey<GetIngestionJobSchema, GetIngestionJobParameters>, updater: Updater<NoInfer<OperationInfiniteData<GetIngestionJobData, GetIngestionJobParameters>> | undefined, NoInfer<DeepReadonly<OperationInfiniteData<GetIngestionJobData, GetIngestionJobParameters>>> | undefined>, options?: SetDataOptions): OperationInfiniteData<GetIngestionJobData, GetIngestionJobParameters> | undefined;
        /** @summary Get Ingestion Job */
        setQueriesData<TInfinite extends boolean = false>(filters: QueryFiltersByParameters<GetIngestionJobSchema, GetIngestionJobData, TInfinite, GetIngestionJobParameters, GetIngestionJobError> | QueryFiltersByQueryKey<GetIngestionJobSchema, GetIngestionJobData, TInfinite, GetIngestionJobParameters, GetIngestionJobError>, updater: Updater<NoInfer<GetIngestionJobData> | undefined, NoInfer<GetIngestionJobData> | undefined>, options?: SetDataOptions): Array<GetIngestionJobData | undefined>;
        /** @summary Get Ingestion Job */
        invalidateQueries<TInfinite extends boolean = false>(filters?: InvalidateQueryFilters<GetIngestionJobSchema, GetIngestionJobData, TInfinite, GetIngestionJobParameters, GetIngestionJobError>, options?: InvalidateOptions): Promise<void>;
        /** @summary Get Ingestion Job */
        refetchQueries<TInfinite extends boolean = false>(filters?: QueryFiltersByParameters<GetIngestionJobSchema, GetIngestionJobData, TInfinite, GetIngestionJobParameters, GetIngestionJobError> | QueryFiltersByQueryKey<GetIngestionJobSchema, GetIngestionJobData, TInfinite, GetIngestionJobParameters, GetIngestionJobError>, options?: RefetchOptions): Promise<void>;
        /** @summary Get Ingestion Job */
        cancelQueries<TInfinite extends boolean = false>(filters?: QueryFiltersByParameters<GetIngestionJobSchema, GetIngestionJobData, TInfinite, GetIngestionJobParameters, GetIngestionJobError> | QueryFiltersByQueryKey<GetIngestionJobSchema, GetIngestionJobData, TInfinite, GetIngestionJobParameters, GetIngestionJobError>, options?: CancelOptions): Promise<void>;
        /** @summary Get Ingestion Job */
        removeQueries<TInfinite extends boolean = false>(filters?: QueryFiltersByParameters<GetIngestionJobSchema, GetIngestionJobData, TInfinite, GetIngestionJobParameters, GetIngestionJobError> | QueryFiltersByQueryKey<GetIngestionJobSchema, GetIngestionJobData, TInfinite, GetIngestionJobParameters, GetIngestionJobError>): void;
        /** @summary Get Ingestion Job */
        resetQueries<TInfinite extends boolean = false>(filters?: QueryFiltersByParameters<GetIngestionJobSchema, GetIngestionJobData, TInfinite, GetIngestionJobParameters, GetIngestionJobError> | QueryFiltersByQueryKey<GetIngestionJobSchema, GetIngestionJobData, TInfinite, GetIngestionJobParameters, GetIngestionJobError>, options?: ResetOptions): Promise<void>;
        /** @summary Get Ingestion Job */
        isFetching<TInfinite extends boolean = false>(filters?: QueryFiltersByParameters<GetIngestionJobSchema, GetIngestionJobData, TInfinite, GetIngestionJobParameters, GetIngestionJobError> | QueryFiltersByQueryKey<GetIngestionJobSchema, GetIngestionJobData, TInfinite, GetIngestionJobParameters, GetIngestionJobError>): number;
        schema: GetIngestionJobSchema;
        types: {
            parameters: GetIngestionJobParameters;
            data: GetIngestionJobData;
            error: GetIngestionJobError;
        };
    };
}
/** @summary Get Ingestion Job */
export const getIngestionJob = {
    schema: {
        method: "get",
        url: "/ingestion-jobs/{job_id}"
    }
} as {
    schema: GetIngestionJobSchema;
    [QraftServiceOperationsToken]: IngestionJobsService["getIngestionJob"];
};
export const ingestionJobsService = {
    getIngestionJob
} as const;
type GetIngestionJobSchema = {
    method: "get";
    url: "/ingestion-jobs/{job_id}";
};
type GetIngestionJobParameters = paths["/ingestion-jobs/{job_id}"]["get"]["parameters"];
type GetIngestionJobData = paths["/ingestion-jobs/{job_id}"]["get"]["responses"]["200"]["content"]["application/json"];
type GetIngestionJobError = paths["/ingestion-jobs/{job_id}"]["get"]["responses"]["422"]["content"]["application/json"];
